# Generated by Django 3.2.20 on 2023-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('stars', models.IntegerField(null=True)),
                ('numberreviews', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('productpic', models.URLField()),
                ('amazon', models.URLField()),
            ],
        ),
    ]
