# Generated by Django 3.2.20 on 2023-10-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactform',
            new_name='contact',
        ),
    ]
