# Generated by Django 3.2.20 on 2023-08-19 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateField(default=datetime.date(2023, 8, 19)),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily_Goal'), ('W', 'Weekly_Goal'), ('M', 'Monthly_Goal'), ('Y', 'Yearly_Goal')], default='Daily', max_length=10),
        ),
    ]
