# Generated by Django 3.2.20 on 2023-08-24 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230819_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('A', 'A Urgent'), ('B', 'B Important'), ('C', 'C OK'), ('D', 'D Delegate'), ('E', 'E Eliminate')], default='A_Urgent', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(default=datetime.date(2023, 8, 24)),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily Goal'), ('W', 'Weekly Goal'), ('M', 'Monthly Goal'), ('Y', 'Yearly Goal')], default='Daily', max_length=10),
        ),
    ]
