# Generated by Django 3.2.20 on 2023-10-08 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231007_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactF',
            new_name='Contact',
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(default=datetime.date(2023, 10, 8)),
        ),
    ]
