# Generated by Django 3.2.20 on 2023-08-26 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230824_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(default=datetime.date(2023, 8, 26)),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Important', 'Important'), ('OK', 'OK'), ('Delegate', 'Delegate'), ('Eliminate', 'Eliminate')], default='Urgent', max_length=10),
        ),
    ]
