# Generated by Django 3.2.20 on 2023-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20231009_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberreviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
