# Generated by Django 3.2.20 on 2023-10-11 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateField(default=datetime.date(2023, 10, 11)),
        ),
    ]
