# Generated by Django 3.2.20 on 2023-10-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20231020_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser1',
        ),
    ]
